### ISSUE TITLE
based

### ISSUE THREAD

**Issue by Gopro336** [jeremypelletier/novoline#8]
do what I did here:
https://github.com/Gopro336/Konas-Deobf-Remap

**Comment by jeremypelletier** [comment]
What part?

**Comment by Gopro336** [comment]
I mean rename the method and field names to vaild ones

**Comment by Gopro336** [comment]
and manually remap some of the classes to aid readability

**Comment by jeremypelletier** [comment]
> I mean manually remap some of the classes/methods/fields to aid readability

What isn't readable? Nearly all the minecraft classes are fully remapped and majority of the client is as well. Sure, the modules can be cleaned up a bit, but it is not worth my time.

**Comment by Gopro336** [comment]
ok

**Comment by Gopro336** [comment]
oh shit, looking in wrong folder lol. Nice job
